Hw 2 (Scrapper: Clients)
Pacan4ik/tinkoff-course-spring2023 pull request #2
Opened 2024-02-23 18:03 UTC by Pacan4ik

2024-02-29 13:36 UTC, nexen505 requested changes

2024-02-29 13:36 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/LinkUpdateScheduler.java
> +    @Scheduled(fixedDelayString = "#{@scheduler.interval()}")
Косметика: можно упростить выражение, если воспользоваться знаком $ для получения конфигурационного свойства приложения.

2024-02-29 13:36 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/clients/Client.java
> +        WebClient webClient = WebClient.builder().baseUrl(baseUrl).build();
Проблема: клиент создается каждый раз за ненадобностью.

Предложение: создать его один раз и воспользоваться предконфигурированным со стороны Spring Boot компонентом `WebClient.Builder builder`, чтобы не терять возможности, преднастроенным фреймворком.

2024-02-29 13:36 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
> +    @Bean
Проблема: бины объявлены внутри `ConfigurationProperties` за ненадобностью.

Предложение: перенести бины-клиенты в отдельную `@Configuration`.

2024-03-01 13:31 UTC, Pacan4ik commented on scrapper/src/main/java/edu/java/scrapper/LinkUpdateScheduler.java
> +    @Scheduled(fixedDelayString = "#{@scheduler.interval()}")
Не совсем понимаю. Если пользоваться знаком $ (например так: ```"${app.schdeduler.interval}"```), то я получаю конфигурационные свойства из .yml файла. Тогда теряется настройка интервала через единицы измерения (секунды, миллисекунды), и отпадает необходимость конфигурационного класса. Или есть способ обратиться именно к конфигурационному классу через placeholder?

2024-03-01 13:42 UTC, Pacan4ik commented on scrapper/src/main/java/edu/java/scrapper/clients/Client.java
> +        WebClient webClient = WebClient.builder().baseUrl(baseUrl).build();
Есть ли разница получения инстанса ```WebClient.Builder``` через ```WebClient.builder()``` или через контекст Spring'a? Насколько я понял, во втором случае мы получаем такой же Builder, только с примененным ```customizeProvider```, но из-за этого мне бы пришлось тянуть ```WebClient.Builder``` через все конструкторы, так как клиенты создаются через ```new```. Критично ли это? И как предпочтительнее?

2024-03-05 12:31 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/LinkUpdateScheduler.java
> +    @Scheduled(fixedDelayString = "#{@scheduler.interval()}")
Не теряется: бин-компонент конфигурационного класса заполняется на основе yml-файла. Так что обращение по ключу свойства и обращение к свойству через соответствующий компонент ведут к чтению свойств из yml-файла.

2024-03-05 12:33 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/clients/Client.java
> +        WebClient webClient = WebClient.builder().baseUrl(baseUrl).build();
Предпочтительно как раз пользоваться тем, что Spring Boot предоставляет в контексте, именно по той причине, которую ты объяснил. Протаскивать builder в этом смысле не страшно, на мой взгляд. Страшнее - терять фичи фреймворка.

2024-03-05 12:35 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/LinkUpdateScheduler.java
> +    @Scheduled(fixedDelayString = "#{@scheduler.interval()}")
Кроме того, конфигурационный класс предоставляет фреймворку информацию о том, какого типа поля в соответствующих свойствах лежат, что позволяет настроить их парсинг и т.п.

2024-03-10 07:59 UTC, nexen505 approved these changes

2024-03-10 19:40 UTC, merged