Hw 3
Pacan4ik/tinkoff-course-spring2023 pull request #3
Opened 2024-03-03 15:23 UTC by Pacan4ik

2024-03-03 15:25 UTC, Pacan4ik commented
С настройкой контекста для тестов пока не разобрался

2024-03-13 13:31 UTC, nexen505 requested changes

2024-03-13 13:31 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/api/controllers/DefaultUpdateController.java
> +    UpdateHandlerService updateHandlerService;
Косметика:

```suggestion
    private final UpdateHandlerService updateHandlerService;
```

2024-03-13 13:31 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/configuration/ClientsConfig.java
> +    ApplicationConfig applicationConfig;
Косметика:

```suggestion
    private final ApplicationConfig applicationConfig;
```

2024-03-13 13:31 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/configuration/ClientsConfig.java
> +    WebClient.Builder webClientBuilder;
Косметика:

```suggestion
    private final WebClient.Builder webClientBuilder;
```

2024-03-13 13:31 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/ChatRepository.java
> +        map.put(id, new ArrayList<>());
Проблема: такой список непотокобезопасен, но используется в многопоточной среде.

Предложение: использовать потокобезопасную реализацию.

2024-03-13 13:31 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/controllers/ChatController.java
> +public interface ChatController { //TODO ANNOTATIONS
Вопрос: тут точно еще нужна `TODO`?

2024-03-13 13:31 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/controllers/DefaultChatController.java
> +    ChatRepositoryService chatRepositoryService;
Косметика:

```suggestion
    private final ChatRepositoryService chatRepositoryService;
```

2024-03-13 21:45 UTC, Pacan4ik commented
С тестами вроде всё на место встанет после настройки тестового контейнера в следующих заданиях.

2024-03-19 11:47 UTC, nexen505 approved these changes

2024-03-19 12:00 UTC, merged