Hw 4
Pacan4ik/tinkoff-course-spring2023 pull request #4
Opened 2024-03-07 15:11 UTC by Pacan4ik

2024-03-07 15:16 UTC, Pacan4ik commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            //liquibase.update("", new OutputStreamWriter(System.out));
```liqubase.update(String context)``` deprecated, но если использовать любой Writer, то таблицы не создаются.

2024-03-19 11:53 UTC, nexen505 requested changes

2024-03-19 11:53 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/ContainerTest.java
> +    private static final Connection CONNECTION;
Проблема: ресурс не закрывается.

Предложение: создавать его на уровне каждого отдельного теста и использовать `try-with-resources`.

2024-03-19 11:53 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/ContainerTest.java
> +        ResultSet rs = metaData.getTables(
Проблема: тут и в соседних тестах ресурс не закрывается в случае ошибок теста.

Предложение: использовать `try-with-resources` вместо явного вызова `close`, использованного ниже.

2024-03-19 11:53 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            connection = c.createConnection("");
Проблема: ресурс не закрывается.

Предложение: перенести его в `try-with-resources`.

2024-03-19 11:53 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            Database database =
Проблема: ресурс не закрывается.

Предложение: перенести его в `try-with-resources`.

2024-03-20 13:15 UTC, nexen505 approved these changes

2024-03-20 16:43 UTC, merged