Homework 5 (Domain)
Pacan4ik/tinkoff-course-spring2023 pull request #5
Opened 2024-03-13 20:41 UTC by Pacan4ik

2024-03-26 12:21 UTC, nexen505 requested changes

2024-03-26 12:21 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/dataSources/SupportedLinkProvider.java
> +    boolean isSupports(ParsedUrl parsedUrl);
Опечатка:

```suggestion
    boolean isSupported(ParsedUrl parsedUrl);
```

2024-03-26 12:21 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/services/jdbc/JdbcChatRepositoryService.java
> +        if (chatRepository.find(id).isEmpty()) {
Мысль: думаю, эту логику можно заменить одним запросом `insert into ... on conflict do nothing`.

2024-03-26 12:21 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/services/jdbc/JdbcChatRepositoryService.java
> +    public void deleteChat(Long id) {
Проблема: данный метод сильно нагружает базу, так как порождает большое количество запросов.

Предложение: переделать логику уменьшением числа запросов. Можно сделать несколько `delete` запросов с фильтрацией без доп.чтения.

2024-03-26 12:21 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/services/jdbc/JdbcLinkRepositoryService.java
> +        return linkRepository.findAll(linkIds.toArray(Long[]::new)).stream()
Проблема: два запроса на чтение в БД, хотя можно сделать один.

Предложение: реализовать один запрос на получение ссылок по идентификатору чата.

2024-03-26 12:21 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/domain/dao/ChatRepository.java
> +    List<Long> getAllLinks(Long id);
Мысль: этот метод семантически скорее к `LinkRepository` относится.

2024-03-26 12:21 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/services/jdbc/JdbcLinkRepositoryService.java
> +    public LinkResponse addLink(Long id, URI link) {
Проблема: метод значительно усложнен большим количеством чтений (при добавлении записи с внешним ключом необязательно проверять наличие связанной сущности, так как эта ошибка и так упадет на уровне БД при случае).

Предложение: заменить логику на одну вставку с обработкой конфликта.

2024-03-26 12:21 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/services/jdbc/JdbcLinkRepositoryService.java
> +    public LinkResponse removeLink(Long id, URI link) {
Проблема: логика перегружена запросами к БД.

Предложение: реализовать через несколько запросов (удалить связки, удалить ссылку без связок).

2024-03-26 12:21 UTC, nexen505 commented on migrations/tables.sql
>      id      bigserial primary key,
Мысль: кажется, этот идентификатор не нужен в пользу составного первичного ключа.

2024-03-26 17:56 UTC, Pacan4ik commented
Может стоить убрать суррогатный id у link и в качестве PK использовать url? Тогда можно было бы избавиться от некоторых запросов и в assign таблице сразу делать удаление по url.

2024-03-28 12:16 UTC, nexen505 commented
> Может стоить убрать суррогатный id у link и в качестве PK использовать url? Тогда можно было бы избавиться от некоторых запросов и в assign таблице сразу делать удаление по url.

Думаю, что в данном задании это излишне и потребует значительного рефакторинга, что скорее потратит время.

2024-03-28 12:16 UTC, nexen505 approved these changes

2024-04-02 14:32 UTC, merged