Hw 6 (JPA)
Pacan4ik/tinkoff-course-spring2023 pull request #7
Opened 2024-03-22 11:20 UTC by Pacan4ik

2024-04-08 12:23 UTC, nexen505 requested changes

2024-04-08 12:23 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/services/jpa/JpaChatService.java
> +        linkRepository.deleteAll(
Проблема: это очень жирно выгружать в память все сущности и еще из фетчить LAZY-коллекции.

Предложение: реализовать отдельный JPQL-запрос в репозитории для это операции.

2024-04-08 12:23 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/services/jpa/JpaLinkService.java
> +    public LinkResponse removeLink(Long id, URI url) {
Проблема: реализация в себе включает большое количество запросов к БД.

Предложение: зарефакторить логику на использование JPQL-запросов репозиториев.

2024-04-08 12:23 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/api/services/jpa/JpaLinkService.java
> +    @Transactional
Проблема: транзакция открывается на запись, хотя записи не происходит.

Предложение: использовать `readonly` параметр тут и в других подобных местах в соседних сервисах.

2024-04-08 12:23 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scrapper/scheduling/LinkUpdateScheduler.java
> +import edu.java.scrapper.domain.jdbc.dao.LinkRepository;
Проблема: тут используется JDBC-реализация, хотя по логике задания тут должна быть уже обобщенная.

Предложение: унифицировать репозитории одним интерфейсом на разных реализациях.

2024-04-10 16:49 UTC, Pacan4ik commented on scrapper/src/main/java/edu/java/scrapper/configuration/ObjectMapperUtils.java
> +    }
Не получилось объявить как Bean. При использовании билдера или просто объявления как бина, Spring подхватывает его вместо автоконфигурируемого и из-за этого ломаются Http клиенты.

2024-04-10 16:51 UTC, Pacan4ik commented on scrapper/src/main/java/edu/java/scrapper/domain/jpa/dao/ChatRepository.java
> +           nativeQuery = true)
JPQL использовать не стал, остановился на nativeQuery, потому что я не объявлял link_chat_assignment как отдельную сущность

2024-04-15 05:55 UTC, nexen505 approved these changes

2024-04-15 19:44 UTC, merged